#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : ddt
Version  : 1.2.0
Release  : 26
URL      : http://pypi.debian.net/ddt/ddt-1.2.0.tar.gz
Source0  : http://pypi.debian.net/ddt/ddt-1.2.0.tar.gz
Summary  : platform-agnostic video game programming tools
Group    : Development/Tools
License  : MIT
Requires: ddt-license = %{version}-%{release}
Requires: ddt-python = %{version}-%{release}
Requires: ddt-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3

%description
[![Build Status](https://travis-ci.org/txels/ddt.svg)](https://travis-ci.org/txels/ddt)
[![Code Health](https://landscape.io/github/txels/ddt/master/landscape.svg)](https://landscape.io/github/txels/ddt/master)
<!-- [![Can I Use Python 3?](https://caniusepython3.com/project/ddt.svg)](https://caniusepython3.com/project/ddt) -->
[![codecov.io](https://codecov.io/github/txels/ddt/coverage.svg?branch=master)](https://codecov.io/github/txels/ddt)
[![Version](https://img.shields.io/pypi/v/ddt.svg)](https://pypi.python.org/pypi/ddt)
[![Downloads](https://img.shields.io/pypi/dm/ddt.svg)](https://pypi.python.org/pypi/ddt)

%package license
Summary: license components for the ddt package.
Group: Default

%description license
license components for the ddt package.


%package python
Summary: python components for the ddt package.
Group: Default
Requires: ddt-python3 = %{version}-%{release}

%description python
python components for the ddt package.


%package python3
Summary: python3 components for the ddt package.
Group: Default
Requires: python3-core
Provides: pypi(ddt)

%description python3
python3 components for the ddt package.


%prep
%setup -q -n ddt-1.2.0
cd %{_builddir}/ddt-1.2.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1582916075
# -Werror is for werrorists
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$CFLAGS -fno-lto "
export FFLAGS="$CFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/ddt
cp %{_builddir}/ddt-1.2.0/LICENSE.md %{buildroot}/usr/share/package-licenses/ddt/30ab786d0202a61aa52d094bc66753260a292b00
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/ddt/30ab786d0202a61aa52d094bc66753260a292b00

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
