#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : ddt
Version  : 1.1.0
Release  : 8
URL      : http://pypi.debian.net/ddt/ddt-1.1.0.tar.gz
Source0  : http://pypi.debian.net/ddt/ddt-1.1.0.tar.gz
Summary  : Data-Driven/Decorated Tests
Group    : Development/Tools
License  : MIT
Requires: ddt-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : setuptools

%description
No detailed description available

%package python
Summary: python components for the ddt package.
Group: Default

%description python
python components for the ddt package.


%prep
%setup -q -n ddt-1.1.0

%build
export LANG=C
python2 setup.py build -b py2

%install
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
